pipeline {
    agent any
    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/your-username/DevOps-Pipeline.git'
            }
        }
        stage('Build & Push Docker Image') {
            steps {
                sh 'docker build -t 651706743487.dkr.ecr.us-east-1.amazonaws.com/myapp:latest .'
                sh 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 651706743487.dkr.ecr.us-east-1.amazonaws.com'
                sh 'docker push 651706743487.dkr.ecr.us-east-1.amazonaws.com/myapp:latest'
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/deployment.yaml'
                sh 'kubectl apply -f k8s/service.yaml'
            }
        }
    }
}
